# Generated by Django 5.2.13 on 2026-05-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='public_id',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
