# Generated by GitHub Copilot on 2026-05-05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("matches", "0002_match_public_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lobby",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(blank=True, editable=False, null=True, unique=True)),
                ("name", models.CharField(max_length=64, unique=True)),
                ("state", models.CharField(choices=[("open", "Open"), ("full", "Full"), ("in_match", "In Match"), ("closed", "Closed")], default="open", max_length=16)),
                ("categories", models.JSONField(blank=True, default=list)),
                ("question_types", models.JSONField(blank=True, default=list)),
                ("difficulties", models.JSONField(blank=True, default=list)),
                ("map_radius", models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(5)])),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("guest", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="joined_lobbies", to=settings.AUTH_USER_MODEL)),
                ("host", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="hosted_lobbies", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="match",
            name="lobby",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="matches", to="matches.lobby"),
        ),
        migrations.AddField(
            model_name="match",
            name="result_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="match",
            name="settings_data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
