# Generated by GitHub Copilot on 2026-05-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="display_name",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
